(default) void m1()
static void m2()
public int add(int a,intb)
public static void main(String []args)
public static void main(String []args)
public static void main(String args[])
public static void main(String []hello)
public static void main(String []args)
public static synchronized strictfp void main(string []args)
